---
repos:
  -   repo: https://github.com/pre-commit/mirrors-yapf
      rev: '79fc0d8'
      hooks:
        - id: yapf
          args: [-r]

  -   repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
        - id: isort
          name: isort

  -   repo: https://gitlab.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
        - id: flake8
          args: [--count, --show-source, --statistics]

  -   repo: https://github.com/pycqa/pydocstyle
      rev: 6.1.1
      hooks:
          - id: pydocstyle
            exclude: ^(test/)|(docs/)|(examples/)|(setup.py)
